### PR TITLE
Added tip for starting in fullscreen mode.

### PR DESCRIPTION
**Pull request by chr15m**

### CODE REVIEW

**Comment by lambdalisue** [comment]
I'm sorry but I think it's beyond this plugin's responsibility. For example, your example would register the autocmd twice when user reload his/her vimrc and I don't think this plugins should explain how to prevent that.

**Comment by chr15m** [comment]
Ok, understood! It took me quite some time to figure out myself how to do this so I thought it might be useful to other people. I'll figure out some other place to make this information easier to find. Thank you for your consideration & for the plugin which I use all the time!

**Comment by lambdalisue** [comment]
Thanks for understanding. Well https://github.com/lambdalisue/vim-fullscreen/wiki is free space to write tips 👍

**Comment by chr15m** [comment]
:+1: ok thanks!

**Pull request closed without merging**
